name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, curl, dom, fileinfo, intl, json, mysql, pdo, tokenizer, xml, zip
          tools: composer

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Set permissions
        run: chmod -R 755 .

      - name: Create ZIP deployment bundle
        run: |
          zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: trendigle-api
          environment_name: trendigle-api-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
