name: Deploy Laravel to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, curl, dom, fileinfo, json, mysql, openssl, pdo, tokenizer, xml
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Run Laravel build (optional)
        run: php artisan config:cache

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: trendigle-api
          environment_name: trendigle-api-env
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

      - name: Create ZIP archive
        run: zip -r deploy.zip . -x "*.git*" "vendor/*" "node_modules/*" ".github/*"
